# Generated by Django 4.1.5 on 2023-01-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='name',
        ),
    ]
